### ISSUE TITLE
Consider switching the build system.

### ISSUE THREAD

**Issue by nemerle** [thunder-engine/thunder#149]
Qbs is [being deprecated](https://blog.qt.io/blog/2018/10/29/deprecation-of-qbs/), so switching to another build system might be needed at some point.

Thunder could follow the Qt project itself and switch to using CMake?

I've managed to cobble a CMake project that seems to work a little bit, so at least it's not impossible :smile:

**Comment by eprikazchikov** [comment]
Hi, yes I know about this sad news =( They will not going to introduce new features but qbs will not disappear immediately. At this moment it's doing all we need to build a project and natively supported by Qt Creator. It's much faster and flexible then QMake btw QMake is also not growing. CMake is also in my field of view but when I used it in my previous project, I faced a lot of problems like frameworks version conflicts (when you have several Qt versions or several OpenSSL versions and etc) it peeks the version with internal logic and it was hard to do it right with undocumented variables. But anyway thanks for your proposal. I will think about this.

**Comment by eprikazchikov** [comment]
Just wanted to add. Thunder is using qbs as an internal build tool. To build your game project WorldEditor will use Builder tool which packs your resources and build your binaries. It uses qbs in the last step. I mean, switch to CMake will require to modify this logic. But yes, it's not impossible.

**Comment by eprikazchikov** [comment]
> I've managed to cobble a CMake project that seems to work a little bit, so at least it's not impossible.
Does it mean you are ready to do this for ThunderEngine?

**Comment by eprikazchikov** [comment]
I guess this issue can be closed now
