### ISSUE TITLE
Resources: Spine 2D Importer

### ISSUE THREAD

**Issue by eprikazchikov** [thunder-engine/thunder#29]
As an Artist i would like to import Spine 2D format

**Comment by bedwardly-down** [comment]
I know this is old, but have you seen the current license? Spine is great and well maintained but implementing it directly into your engine would require anyone that develops with it to have a paid license to use your engine: https://github.com/EsotericSoftware/spine-runtimes?tab=readme-ov-file#licensing . It’d be great to implement but would probably be best implemented as a separate repo that can be optionally added and built if found in the root repo with a warning about the licensing.

Here’s the C Api for Inochi2D, an open source alternative that is licensed in a more friendly way for Indie developers (not sure how stable or viable it would be at this stage): https://github.com/Inochi2D/inochi2d-c

**Comment by bedwardly-down** [comment]
Just messed around with building the spine-runtime on FreeBSD and the GLFW version would probably require some heavy modifications to build properly (right now, it doesn't detect system libraries and headers properly), but the C and C++ targets build and link without issues. I also know that if you were to go Live2D (which is used mostly for VTuber models but lately has also been used like Spine to rig game models), its native framework builds without too many issues (but the core library would still need to be ran through something like WINE or the Linux binary compatibility to fully support all that can be done with it in a game engine): https://github.com/Live2D/CubismNativeFramework

**Comment by eprikazchikov** [comment]
The first iteration of Spine support will not have Skinned meshes and blend shapes.
