### ISSUE TITLE
Editor: The 2D-3D mode change button does not change its name to 3D when you switch it.

### ISSUE THREAD

**Issue by AlexKiryanov** [thunder-engine/thunder#292]
The 2D-3D mode change button does not change its name to 3D when you switch it.
When you press the 2D-3D mode change button, the viewport 
changes but the button name does not change
![1](https://user-images.githubusercontent.com/65244629/101459067-cfb36080-3948-11eb-90e0-c2247d77eb0e.jpg)
![2](https://user-images.githubusercontent.com/65244629/101459070-d0e48d80-3948-11eb-85af-56d01bfaa0cd.jpg)

**Comment by eprikazchikov** [comment]
2D Button now highlighted when enabled
