### ISSUE TITLE
Editor: Crash on the start screen.

### ISSUE THREAD

**Issue by eprikazchikov** [thunder-engine/thunder#369]
## Description

Crash on the start screen.

## Prerequisites

The Editor is up but the project was not opened

## Steps to Reproduce

1. Click on the File menu

### Expected behavior:

Menu is opened

### Actual behavior:

Application crashed

### Reproducibility:

Constantly on Ubuntu 20.4 in the release mode

## Versions

2021.2

## Additional Information

N/A

**Comment by ruaivantso** [comment]
The issue was checked on Ubuntu 20.04 - it is worked as expected now.

The issue can be closed.
