### ISSUE TITLE
'WorldEditor' crashes on project creation

### ISSUE THREAD

**Issue by ruaivantso** [thunder-engine/thunder#371]
## Description

'WorldEditor' crashes on project creation

## Prerequisites

The tool is built on b8fbf19d commit

## Steps to Reproduce

Start the tool -> press [New] -> set new project name in opened file dialog -> press [Save]

### Expected behavior:
The dialog closes and user can see Idle view

### Actual behavior:
The tool crashes

### Reproducibility:
3/3, 100% 

## Versions
b8fbf19d commit

## Additional Information
**1)** work log of the tool
_$ ./release/install-root/sdk/2021.2/linux/x86_64/bin/WorldEditor &
[1] 5945
$ defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.audiodecode"
libpng error: unexpected zlib return code
libpng error: unexpected zlib return code
QImage::scaled: Image is a null image
libpng error: unexpected zlib return code
 [ FileIO ] Can't open file index
 [ FileIO ] Can't open file AngelBinary
 reload Filed to load a script
./release/install-root/sdk/2021.2/linux/x86_64/bin/WorldEditor: symbol lookup error: /home/irisha/Utils/ThunderEngine/release/install-root/sdk/2021.2/linux/x86_64/bin/plugins/libmedia-editor.so: undefined symbol: alcOpenDevice_

**2)** If the tool is re-started after crash then user can see created project but click on project widget leads to the tool crash

**Comment by eprikazchikov** [comment]
Seems like you have to install OpenAL.
