### ISSUE TITLE
Build procedure is failed

### ISSUE THREAD

**Issue by ruaivantso** [thunder-engine/thunder#453]
## Description

There are suspicious moments in generated 'application.cpp' file 

## Prerequisites

World editor is successfully started and a project is loaded

## Steps to Reproduce

File->Build project->Build for Desktop

### Expected behaviour:

Build is successful

### Actual behaviour:

I can see the following build error:

> [QbsBuilder] ERROR: /usr/bin/clang++ -O2 -Wall -Wextra -target x86_64-pc-linux-gnu -pipe -fexceptions -fvisibility=default -fPIC -DNDEBUG -I/home/irisha/Utils/build-Thunder-Desktop_Qt_5_14_2_GCC_64bit-Debug/Debug/install-root/sdk/2021.4/include/engine -I/home/irisha/Utils/build-Thunder-Desktop_Qt_5_14_2_GCC_64bit-Debug/Debug/install-root/sdk/2021.4/include/modules -I/home/irisha/Utils/build-Thunder-Desktop_Qt_5_14_2_GCC_64bit-Debug/Debug/install-root/sdk/2021.4/include/next -I/home/irisha/Utils/build-Thunder-Desktop_Qt_5_14_2_GCC_64bit-Debug/Debug/install-root/sdk/2021.4/include/next/math -I/home/irisha/Utils/build-Thunder-Desktop_Qt_5_14_2_GCC_64bit-Debug/Debug/install-root/sdk/2021.4/include/next/core -std=c++14 -o /home/irisha/projects/ThunderTest/camera_move/cache/desktop/release/camera-move.90798c63/3a52ce780950d4d9/application.cpp.o -c /home/irisha/projects/ThunderTest/camera_move/cache/generated/application.cpp
 [QbsBuilder] ERROR: /home/irisha/projects/ThunderTest/camera_move/cache/generated/application.cpp:8:10: fatal error: 'modulecamera_move.h' file not found
> [QbsBuilder] #include <modulecamera_move.h>
> [QbsBuilder]          ^~~~~~~~~~~~~~~~~~~~~
> [QbsBuilder] 1 error generated.
> [QbsBuilder] ERROR: Process failed with exit code 1.
 
 1) modulecamera_move.h does not exist and as I understand line 8 can be excluded from 'application.cpp' because of needed functionality is in included 'plugin.cpp' 
 2) I can see in application.cpp (please see it in attached ZIP) that 20 and 22 lines are the same - is it right?

### Reproducibility:

100%

## Versions

Build Version: 2021.4
Build Revision: f01a1ce81b98b095919c547fda2787560bf413c4
Build CPU Architecture: x86_64
OS Name: Ubuntu 20.04.3 LTS
OS CPU Architecture: x86_64
Kernel version: 5.4.0-92-generic
[camera_move.zip](https://github.com/thunder-engine/thunder/files/7832496/camera_move.zip)

**Comment by eprikazchikov** [comment]
In the attached project, I can see the class that was automatically generated in plugin.cpp. This class was included in the wrong place. The root cause is unclear at this point. Please delete the generated directory and try again.

**Comment by ruaivantso** [comment]
Build Version: 2021.4
Build Revision: f01a1ce81b98b095919c547fda2787560bf413c4
Build CPU Architecture: x86_64
OS Name: Ubuntu 20.04.3 LTS
OS CPU Architecture: x86_64
Kernel version: 5.4.0-92-generic

The issue is not reproduced now (last origin/master) and can be closed.
