### ISSUE TITLE
How to use socket?

### ISSUE THREAD

**Issue by toutiewa** [thunder-engine/thunder#460]
## Is your feature request related to a problem? Please describe.

How to use socket?

**Comment by eprikazchikov** [comment]
Could you please provide more details? Are You talking about network sockets? Currently, the engine has no network functionality out of the box. Please specify the code approach in your project. C++ or Angel Script?

**Comment by toutiewa** [comment]
> 你能提供更多细节吗？你在谈论网络套接字吗？目前，该引擎没有开箱即用的网络功能。请在您的项目中指定代码方法。C++ 还是天使脚本？

thanks

**Comment by eprikazchikov** [comment]
I have a branch with the started implementation of network functionality. But nobody requested this until this moment. I believe I need to return to this.
