### ISSUE TITLE
why  [ FileIO ] Can't open file AngelBinary?

### ISSUE THREAD

**Issue by toutiewa** [thunder-engine/thunder#461]
why  [ FileIO ] Can't open file AngelBinary?

 [ FileIO ] Can't open file AngelBinary
 AngelSystem::reload Filed to load a script

**Comment by eprikazchikov** [comment]
This is not a necessary message from the AngelScript module. It means this module is unable to load a related resource. In case you are not using scripts in your projects, this message can be ignored. However, I have fixed this message already. It will not appear in the next releases.
