### ISSUE TITLE
Editor: Content Browser tree view menu

### ISSUE THREAD

**Issue by eprikazchikov** [thunder-engine/thunder#56]
## Description

There is no menu for Content Browser tree view

## Steps to Reproduce

    1. Launch World Editor
    2. Do the right click on tree view in Content Browser

### Expected behavior:

Context menu appeared with options: New Folder, Remove, Rename etc

### Actual behavior:

No context menu.

### Reproducibility:

N/A

## Versions

release-2.0

## Additional Information

N/A

**Comment by gguedesaz** [comment]
I'd like to check this issue.
