### ISSUE TITLE
Editor: The editor only displays a white window when started.

### ISSUE THREAD

**Issue by saierXP** [thunder-engine/thunder#613]
## Description

Running the 2023.2release version of the editor on windows 10, it only displays a white window after startup. But if you enter any parameter in cmd it opens the editor, but there is no window to create a project.
In the 2023.1 release version, the create project window is visible.

## Prerequisites

Run 2023.2/windows/bin/WorldEditor.exe

## Steps to Reproduce

N/A

### Expected behavior:

Show the Create Project window.

### Actual behavior:

Show the white window.

### Reproducibility:

2023.2 All
2023.1 No

## Versions

Build Version: 2023.2
Build Revision: dfa689874412cf9de6fd58a950bc4e54de302370
Build CPU Architecture: x86_64
OS Name: Windows 10 Version 2009
OS CPU Architecture: x86_64
Kernel version: 10.0.19045
GPU: AMD Radeon(TM) Vega 8 Graphics integrated 
GPU Driver: 23.5.2

## Additional Information

![WorldEditor_ixkbjULuCw](https://github.com/thunder-engine/thunder/assets/45038185/c13cd99b-9596-4c80-a502-f83450b63b54)
![WorldEditor_XUKRrD9CBi](https://github.com/thunder-engine/thunder/assets/45038185/c328e24c-b933-4f4d-97a6-fe207145e3cd)

**Comment by eprikazchikov** [comment]
Thank you to highlight this regression to me!

**Comment by eprikazchikov** [comment]
The root cause of this issue related to additional dependency Qt5QmlWorkerScript.dll appeared in new version of Qt
