### ISSUE TITLE
Editor: Editor crash after adding second emitter to the system

### ISSUE THREAD

**Issue by Tnnv** [thunder-engine/thunder#729]
## Description

Editor crashed after adding second emitter to the system. Now opening the system and selecting second emitter leads to a new crash.

## Steps to Reproduce

1. Open attached project
2. Open particle system \content\Textures\ProjectileParticle.efx
3. Select second emitter

### Actual behavior:

Editor crash

## Additional Information

[TurnBased.zip](https://github.com/thunder-engine/thunder/files/14910339/TurnBased.zip)

**Comment by eprikazchikov** [comment]
Effect now limited by only one emitter
