### ISSUE TITLE
Editor: Workspace require resetting after Editor crash

### ISSUE THREAD

**Issue by Tnnv** [thunder-engine/thunder#739]
## Description

Editor workspace require resetting after Editor crash. Main viewport is missing and assets are not opening because of this (probably just don't display specific editor window because of missing viewport). Attempt to save at this state lead to Editor crash.

Resetting workspace fix this.

Build Version: 2024.2
Build Revision: 7cd6db2acf5687b002741e927399cdfb20b26898
Build CPU Architecture: x86_64
OS Name: Windows 10 Version 2009
OS CPU Architecture: x86_64
Kernel version: 10.0.19045

**Comment by bedwardly-down** [comment]
From your crash, do you have a file that ends with the .core extension? I'm not sure how useful those will be but I wonder if your crash and mine are the same. Mine crashes after loading a project but shows this from the gdb dump on crash:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
Address not mapped to object.
0x0000000824420e4b in PluginManager::createRenderer() const ()
   from /home/brad/git/thunder-build/engine/libengine-editor.so
```

**Comment by eprikazchikov** [comment]
This is different one for sure

**Comment by bedwardly-down** [comment]
Do you have an idea of what's causing this one?

**Comment by eprikazchikov** [comment]
Seems like render plugin was not loaded. do you have a full log. I bet there some message about rendergl-editor.so

**Comment by bedwardly-down** [comment]
I meant what's causing their issue. :joy_cat: 

Where do I find that log? I'm guessing I need to enable debug logging?

**Comment by eprikazchikov** [comment]
Could add a full console output? From the begging of console?

**Comment by bedwardly-down** [comment]
I’ve got to test it but I discovered that a system update broke my graphics drivers. That would cause my issue

**Comment by bedwardly-down** [comment]
No logs (other than what I've shared), but I have a lead. PluginManager is definitely written incorrectly for Linux and BSD. Doing a quick test before work but may have a fix here in a bit. I downloaded the Linux build and saw exactly what I needed there.

**Comment by eprikazchikov** [comment]
Hm Ubuntu works well before

**Comment by eprikazchikov** [comment]
I'm unable to reproduce this issue.
