### ISSUE TITLE
Editor: Changing text color in label changes parent background color

### ISSUE THREAD

**Issue by Tnnv** [thunder-engine/thunder#746]
## Description

Changing text color in label component changes background color of parent image component.
Tested in prefab, but was also encountered on the main scene.

Example prefab: Units/UnitWidget
![01](https://github.com/thunder-engine/thunder/assets/80332087/e8ef4514-e97b-4f2a-aa18-e2ead9e1490e)
![02](https://github.com/thunder-engine/thunder/assets/80332087/01fab991-22bd-484d-8d7b-6209a7dd55c7)

## Additional Information

[TurnBased.zip](https://github.com/thunder-engine/thunder/files/14947582/TurnBased.zip)

**Comment by eprikazchikov** [comment]
Unable to reproduce issue on latest build
![image](https://github.com/user-attachments/assets/c5474240-af05-4977-8bfd-ac0dc13b342f)

**Comment by Tnnv** [comment]
Text color correctly changes in the latest build of the Engine, without affecting the background.
