### ISSUE TITLE
Bug: Shaders Have Different MD5Sums Between Windows and Linux SDK Builds From Github Runner Builds

### ISSUE THREAD

**Issue by bedwardly-down** [thunder-engine/thunder#784]
## Description

I was checking to see differences between the FreeBSD, Windows and Linux builds for #778 to see if something was happening to cause some of the resources to not load properly and decided to just run md5sum on some of the shaders. I chose one that doesn't load on the BSD build for this test.

## Prerequisites

Not applicable here.

## Steps to Reproduce

1. Download the Windows and Linux artifacts from here: https://github.com/thunder-engine/thunder/actions/runs/9771559828
2. Extract each to a separate directory.
3. Run `md5sum release/install-root/sdk/2024.2/resources/engine/materials/DefaultFont.shader` from the Windows extraction directory.
4. Repeat with the Linux extraction directory.

### Expected behavior:

Shaders should have the same MD5Sums if they are just copied over and not processed based on platform.

### Actual behavior:

The MD5Sums are drastically different.

### Reproducibility:

Can repeat with the last stable release builds too.

## Versions

Not applicable in this case.

## Additional Information

This may not be a bug but an intended outcome. I haven't fully figured out how resources are processed yet. Both the Linux and BSD MD5Sums are exactly the same between builds. If this is a bug, I wonder if this could be related to them not loading correctly.

Attached is a list of my MD5Sum findings for this test. The lines with `windows-stable` and `linux-stable` are tests ran on the last stable release build from [here](https://github.com/thunder-engine/thunder/releases). The others are from this PR https://github.com/thunder-engine/thunder/pull/777
[md5sum.txt](https://github.com/user-attachments/files/16094744/md5sum.txt)

**Comment by eprikazchikov** [comment]
MD5 check sums was done on top of QT. I'm not controlling this. I can assume these sums was not updated in time when I changed the content. It's not lead to any issues except re import asset if sum doesn't match

**Comment by bedwardly-down** [comment]
I'll close this then. Better safe than sorry in this case.
