### ISSUE TITLE
Feature: Move the resources under worldeditor/bin to an external repository and pull them at the end of the build chain

### ISSUE THREAD

**Issue by bedwardly-down** [thunder-engine/thunder#794]
## Is your feature request related to a problem? Please describe.
Right now, they are part of the main source code repository. With the caching system from #793 , they could possibly bloat the cache, especially if any processing gets done during the build phase.

## Describe the solution you'd like
Moving them to an external repository is a common practice for engine development, especially if they aren't constantly modified. My proposed solution would be to have the engine and tools build first and then pull the binary repository into the sdk distribution itself. This solution could also allow for platform separation if different resources need to be used for different platforms. Look at custom formats for consoles or HLSL vs GLSL shaders for examples. Another example would be, for FreeBSD, the shaders may need custom tweaks that would not apply to other platforms, so as the main developer of that port, I could maintain that as a separate repository and also directly receive PRs and assistance from that community outside of the main repository.

## Describe alternatives you've considered
I am open to alternatives because there are always different, better ways to solve problems that my own development experience wouldn't allow me to think of.

**Comment by eprikazchikov** [comment]
Hello, worldeditor/bin size about 480 kilobytes =) And shaders from this derectories can be changed from time to time. This proposal doesn't makes sense ATM
